version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: peer-backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    container_name: peer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
