global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vercel-app'
    static_configs:
      - targets: ['peer-evaluation.vercel.app'] # change based on your Vercel app domain
    metrics_path: '/api/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Only use this in development/testing

rule_files:
  - rules.yml