name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peer-eval-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peer-eval-frontend:latest
    
    # Add after build steps
          
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm ci

      - name: Run tests (frontend)
        run: |
          cd frontend
          npx jest

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm ci

      - name: Run tests (backend)
        run: |
          cd backend
          npx jest

      - name: Set test environment variables
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV
          echo "PORT=4000" >> $GITHUB_ENV

  sonarcloud:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  notify:
    needs: [build-and-push, sonarcloud]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'C08VCBL65S4'  # Replace with your channel ID
          SLACK_MESSAGE: 'Build, tests, and SonarCloud scan passed successfully! 🎉'